apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3Configuration.secret_name }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3Configuration.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3Configuration.AWS_SECRET_ACCESS_KEY }}
type: Opaque