apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  openmetadata-airflow-password: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-mysql-secrets
type: Opaque
data:
  airflow-mysql-password: YWlyZmxvd19wYXNz
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  openmetadata-mysql-password: b3Blbm1ldGFkYXRhX3Bhc3N3b3Jk
