apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openmetadata-vs
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | required "\nValid .Values.ezua.virtualService.endpoint is required !" }}
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: openmetadata.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8585
